CREATE TABLE PROFESSOR (
	CODPROFESSOR INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(200),
	EMAIL NVARCHAR(150),
	CPF NVARCHAR(11),
	RG NVARCHAR(14)
)

INSERT INTO PROFESSOR (NOME, EMAIL, CPF, RG)
VALUES ('WARNER5', 'WARNER@FATEC.BR', '1231222231', 'RG')


INSERT INTO PROFESSOR (NOME)
VALUES ('WARNER')

SELECT * FROM PROFESSOR

UPDATE PROFESSOR SET RG='RG', CPF= '12312312312'
WHERE CODPROFESSOR=1

CREATE TABLE PESSOAS (
	CODPESSIA INT PRIMARY KEY IDENTITY(1,1),
	NOME NVARCHAR(200),
	EMAIL NVARCHAR(100)
)

INSERT INTO PESSOAS (NOME, EMAIL)
SELECT NOME, EMAIL FROM PROFESSOR

SELECT * FROM PESSOAS

--CONTABILIZA UM CERTO GRUPO DE INFORMAÇOES EX: NOME 
SELECT COUNT (NOME), NOME FROM PESSOAS 
GROUP BY NOME

CREATE TABLE VENDAS (
	CODVENDA INT PRIMARY KEY IDENTITY(1,1),
	PRODUTO NVARCHAR(200),
	QTD INT,
	PRECO INT, 
)

INSERT INTO VENDAS (PRODUTO, QTD,PRECO)VALUES('ARROZ ',1,23)						
INSERT INTO VENDAS (PRODUTO, QTD,PRECO)VALUES('FEIJAO',2,8)						
INSERT INTO VENDAS (PRODUTO, QTD,PRECO)VALUES('MACARRAO',1,10)						
INSERT INTO VENDAS (PRODUTO, QTD,PRECO)VALUES('TOMATE',1,10)						
					
--LISTA A CONTAGEM DOS PRODUTOS, A SOMA E A MEDIA DE VENDAS 
SELECT PRODUTO, COUNT(PRODUTO) AS QTD, SUM(PRECO) AS PRECOFINAL, AVG(PRECO) AS MEDIA FROM VENDAS 
GROUP BY PRODUTO

--MOSTRA OS USUARIO COM EMAIL NULO 
SELECT * FROM PROFESSOR WHERE EMAIL IS NULL

-- ATUALIZAR VALORES DA TABELA
UPDATE PROFESSOR SET EMAIL = 'WBREZOLIN@GMAIL.COM', CPF = '333444555', RG = '0202002'
WHERE CODPROFESSOR=2

--LISTA OS OLEMENTOS COM COMEÇO 'AR' E COM PRECO MAIOR QUE 20 
SELECT * FROM VENDAS 
WHERE PRODUTO LIKE '%AR%' AND PRECO > 20

--LISTA OS ELEMENTOS PELO CODIGO
SELECT * FROM VENDAS 
WHERE CODVENDA IN (1,6,11,17)

--PEGA TODOS OS CODIGOS DE VENDAS ENTRE 5 E 10 
SELECT * FROM VENDAS 
WHERE CODVENDA BETWEEN 5 AND 10

--INFROMA A QUANTIDADE DE DIAS COMPARADA COM A DE HOJE
SELECT DATEDIFF(DAY,'2005-02-11', GETDATE()) AS DIAS

SELECT
CASE
	WHEN DATEDIFF(DAY,'2026-03-03', GETDATE()) > 0
	THEN 'VENCIDO'
	ELSE ' A VENCER' END, 
	DATEDIFF(DAY,'2026-03-03', GETDATE())

