CREATE TABLE CLIENTES (
	CODCLIENTE INT PRIMARY KEY IDENTITY (1,1),
	NOME NVARCHAR(160),
)

CREATE TABLE PRODUTO(
	CODPRODUTO INT PRIMARY KEY IDENTITY (1,1),
	DESCRICAO NVARCHAR(200),
	PRECO DECIMAL(7,2),
	CODCATEGORIA INT

)

CREATE TABLE CATEGORIA(
	CODCATEGORIA INT PRIMARY KEY IDENTITY (1,1),
	DESCRICAO NVARCHAR(100)
)

CREATE TABLE PEDIDO(
	CODPEDIDO INT PRIMARY KEY IDENTITY (1,1),
	CODCLIENE INT,
	CODPRODUTO INT,
	QTD INT
)

ALTER TABLE PRODUTO 
ADD CONSTRAINT FK_PRODCAT FOREIGN KEY (CODCATEGORIA)
REFERENCES CATEGORIA(CODCATEGORIA)

ALTER TABLE PEDIDO 
ADD CONSTRAINT FK_PEDCLI FOREIGN KEY (CODCLIENE)
REFERENCES CLIENTES(CODCLIENTE)

ALTER TABLE PEDIDO 
ADD CONSTRAINT FK_PEDPROD FOREIGN KEY (CODPRODUTO)
REFERENCES PRODUTO(CODPRODUTO)

INSERT INTO CLIENTES
VALUES('WARNER'), ('ANA CLARA'), ('JOAO DA SILVA'), ('MARIA JOAQUINA'), ('PELE')

INSERT INTO CATEGORIA 
VALUES ('ALIMENTOS'), ('ELETRONICOS'), ('MEDICAMENTOS')

SELECT *FROM CATEGORIA

INSERT INTO PRODUTO
VALUES ('ARROZ', 23, 1), ('FEIJAO', 12, 1), ('MACARRAO', 6, 1), 
('DIPIRONA', 2, 3), ('OMEPRAZOL', 6, 3), ('DORFELX', 7, 3),
('CELULAR', 1000, 2), ('TV 32POL', 800, 2), ('RADIO', 200, 2)

INSERT INTO PEDIDO
VALUES (1,1,1), (1,4,2), (1,5,1), (2,8,1), (3,9,1), (5,6,3), (5,3,1)


-- INNER JOIN MOSTRA AS TABELAS VINCULADAS A CATEGORIA, MOSTRA TODOS ATIRIBUTOS QUE TEM NAS DEMAIS TABELAS,DEPENDENDO DA SUA AMARRACAO
--COUNT CONTA QUANTOS PRODUTOS TEM POR DESCRICAO QUE É A CATEGORIA

SELECT /*P.DESCRICAO PRODUTOS, P.PRECO,*/ C.DESCRICAO CATEGORIA, COUNT (P.CODPRODUTO) AS QUANTIDADE
FROM PRODUTO P 
RIGHT JOIN CATEGORIA C ON P.CODCATEGORIA=C.CODCATEGORIA
GROUP BY C.DESCRICAO

INSERT INTO CATEGORIA VALUES
('ESPORTE')

SELECT  CL.NOME CLIENTE, PR.DESCRICAO PRODUTO, CA.DESCRICAO CATEGORIA,
PR.PRECO VLRUNIT, PE.QTD, PR.PRECO*PE.QTD VLRTOTAL
FROM CLIENTES CL
INNER JOIN PEDIDO PE ON CL.CODCLIENTE=PE.CODCLIENE
INNER JOIN PRODUTO PR ON PE.CODPRODUTO=PR.CODPRODUTO
INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA=CA.CODCATEGORIA

SELECT  CA.DESCRICAO CATEGORIA, COUNT(PR.CODPRODUTO) AS QTD
FROM PEDIDO PE
INNER JOIN PRODUTO PR ON PE.CODPRODUTO=PR.CODPRODUTO
INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA=CA.CODCATEGORIA
GROUP BY CA.DESCRICAO
ORDER BY 2 DESC 

SELECT  CL.NOME CLIENTE, CA.DESCRICAO CATEGORIA, COUNT(PR.CODPRODUTO) AS QTD
FROM CLIENTES CL
INNER JOIN PEDIDO PE ON CL.CODCLIENTE=PE.CODCLIENE
INNER JOIN PRODUTO PR ON PE.CODPRODUTO=PR.CODPRODUTO
INNER JOIN CATEGORIA CA ON PR.CODCATEGORIA=CA.CODCATEGORIA
GROUP BY CL.NOME, CA.DESCRICAO
ORDER BY QTD DESC