CREATE TABLE CONTA (
    CODCONTA INT PRIMARY KEY IDENTITY(1,1),
    SALDO DECIMAL(7,2) DEFAULT 0 -- Começa com zero
);

CREATE TABLE MOVIMENTACAO(
    CODMOV INT PRIMARY KEY IDENTITY(1,1),
    CODCONTA INT,
    TIPOMOV NVARCHAR(1), -- 'D' ou 'S'
    VALORMOV DECIMAL(7,2),
    DATAMOV DATETIME,
    CONSTRAINT FK_MOVIMENTACAO FOREIGN KEY (CODCONTA) REFERENCES CONTA(CODCONTA)
);
GO

ALTER PROCEDURE ATUALIZA_SALDO(
    @CODCONTA INT,
    @VALORMOV DECIMAL(7,2),
    @TIPOMOV NVARCHAR(1)
) AS 
BEGIN
    DECLARE @SALDO_ATUAL DECIMAL(7,2);
    
    -- Pega o saldo atual para validar o saque depois
    SELECT @SALDO_ATUAL = SALDO FROM CONTA WHERE CODCONTA = @CODCONTA;

    -- LÓGICA DE DEPÓSITO
    IF (@TIPOMOV = 'D')
    BEGIN 
        BEGIN TRANSACTION;
            INSERT INTO MOVIMENTACAO(CODCONTA, TIPOMOV, VALORMOV, DATAMOV)
            VALUES (@CODCONTA, @TIPOMOV, @VALORMOV, GETDATE());

            UPDATE CONTA SET SALDO = (SELECT SALDO + @VALORMOV WHERE CODCONTA = @CODCONTA) WHERE CODCONTA=@CODCONTA;
        COMMIT;
        PRINT 'Depósito de R$ ' + CAST(@VALORMOV AS VARCHAR) + ' realizado.';
    END

    -- LÓGICA DE SAQUE
    ELSE IF (@TIPOMOV = 'S')
    BEGIN
        IF (@SALDO_ATUAL >= @VALORMOV)
        BEGIN
            BEGIN TRANSACTION;
                INSERT INTO MOVIMENTACAO(CODCONTA, TIPOMOV, VALORMOV, DATAMOV)
                VALUES (@CODCONTA, @TIPOMOV, @VALORMOV * -1, GETDATE());

                UPDATE CONTA SET SALDO = (SELECT SALDO - @VALORMOV WHERE CODCONTA = @CODCONTA) WHERE CODCONTA=@CODCONTA;
            COMMIT;
            PRINT 'Saque de R$ ' + CAST(@VALORMOV AS VARCHAR) + ' realizado.';
        END
        ELSE
        BEGIN
            PRINT 'ERRO: Saldo insuficiente!';
        END
    END
END;
GO

INSERT INTO CONTA (SALDO) VALUES (100.00); -- Conta 1 começa com 100 reais
SELECT * FROM CONTA; -- Veja a conta criada

EXEC ATUALIZA_SALDO @CODCONTA = 1, @VALORMOV = 50.00, @TIPOMOV = 'D';

EXEC ATUALIZA_SALDO @CODCONTA = 1, @VALORMOV = 30.00, @TIPOMOV = 'S';

EXEC ATUALIZA_SALDO @CODCONTA = 1, @VALORMOV = 500.00, @TIPOMOV = 'S';

SELECT * FROM CONTA;       
SELECT * FROM MOVIMENTACAO;

